# Generated by Django 4.2.9 on 2024-01-08 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "match_id",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("match_date", models.DateTimeField(verbose_name="Match Date")),
                (
                    "match_team_A",
                    models.CharField(max_length=30, verbose_name="Team A"),
                ),
                (
                    "match_team_B",
                    models.CharField(max_length=30, verbose_name="Team B"),
                ),
                (
                    "match_status",
                    models.SmallIntegerField(default=0, verbose_name="Match Status"),
                ),
                (
                    "match_winner",
                    models.CharField(
                        default=None, max_length=30, verbose_name="Winner"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Submissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "susername",
                    models.CharField(max_length=100, verbose_name="Username"),
                ),
                (
                    "smatch_id",
                    models.PositiveSmallIntegerField(verbose_name="Match ID"),
                ),
                (
                    "predicted_team",
                    models.CharField(max_length=20, verbose_name="Predicted Team"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0, verbose_name="Score")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
