# Generated by Django 4.2.9 on 2024-01-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictsa20", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="match_start_time",
            field=models.TimeField(default="21:00:00", verbose_name="Match Start Time"),
        ),
        migrations.AlterField(
            model_name="match",
            name="match_date",
            field=models.DateField(verbose_name="Match Date"),
        ),
    ]
