# Generated by Django 4.2.9 on 2024-01-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictsa20", "0002_match_match_start_time_alter_match_match_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Foo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_true", models.BooleanField(default=False)),
            ],
        ),
    ]
