# Generated by Django 4.2.9 on 2024-01-23 17:11

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("predictsa20", "0004_foo_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foo",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region="IN"
            ),
        ),
    ]
